"""create ia_rating table

Revision ID: 41012ab3acb0
Revises: 836f084326d9
Create Date: 2026-05-14 11:23:49.760502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41012ab3acb0'
down_revision: Union[str, Sequence[str], None] = '836f084326d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpa_ia_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rating_detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['rpa_scrap_results.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rpa_ia_ratings_created_at_idx', 'rpa_ia_ratings', ['created_at'], unique=False)
    op.create_index('rpa_ia_ratings_result_id_idx', 'rpa_ia_ratings', ['result_id'], unique=False)
    op.drop_column('rpa_scrap_requests', 'total_items')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.add_column('rpa_scrap_requests', sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('rpa_ia_ratings_result_id_idx', table_name='rpa_ia_ratings')
    op.drop_index('rpa_ia_ratings_created_at_idx', table_name='rpa_ia_ratings')
    op.drop_table('rpa_ia_ratings')
    # ### end Alembic commands ###
