"""migração_inicial

Revision ID: 836f084326d9
Revises: 
Create Date: 2026-05-11 21:02:27.475831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836f084326d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='user_status'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('users_email_idx', 'users', ['email'], unique=False)
    op.create_index('users_status_idx', 'users', ['status'], unique=False)
    op.create_index('users_username_idx', 'users', ['username'], unique=False)
    op.create_table('rpa_scrap_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filter_payload', sa.JSON(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rpa_scrap_requests_created_at_idx', 'rpa_scrap_requests', ['created_at'], unique=False)
    op.create_index('rpa_scrap_requests_session_id_idx', 'rpa_scrap_requests', ['session_id'], unique=False)
    op.create_index('rpa_scrap_requests_user_id_idx', 'rpa_scrap_requests', ['requested_by_user_id'], unique=False)
    op.create_table('rpa_scrap_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', name='rpa_request_step'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILURE', 'OCCURRENCE', name='rpa_request_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['rpa_scrap_requests.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rpa_scrap_events_request_id_created_at_idx', 'rpa_scrap_events', ['request_id', 'created_at'], unique=False)
    op.create_index('rpa_scrap_events_request_id_idx', 'rpa_scrap_events', ['request_id'], unique=False)
    op.create_table('rpa_scrap_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['rpa_scrap_requests.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rpa_scrap_results_created_at_idx', 'rpa_scrap_results', ['created_at'], unique=False)
    op.create_index('rpa_scrap_results_request_id_idx', 'rpa_scrap_results', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rpa_scrap_results_request_id_idx', table_name='rpa_scrap_results')
    op.drop_index('rpa_scrap_results_created_at_idx', table_name='rpa_scrap_results')
    op.drop_table('rpa_scrap_results')
    op.drop_index('rpa_scrap_events_request_id_idx', table_name='rpa_scrap_events')
    op.drop_index('rpa_scrap_events_request_id_created_at_idx', table_name='rpa_scrap_events')
    op.drop_table('rpa_scrap_events')
    op.drop_index('rpa_scrap_requests_user_id_idx', table_name='rpa_scrap_requests')
    op.drop_index('rpa_scrap_requests_session_id_idx', table_name='rpa_scrap_requests')
    op.drop_index('rpa_scrap_requests_created_at_idx', table_name='rpa_scrap_requests')
    op.drop_table('rpa_scrap_requests')
    op.drop_index('users_username_idx', table_name='users')
    op.drop_index('users_status_idx', table_name='users')
    op.drop_index('users_email_idx', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
